#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

#Git Config
git config --global core.editor "code --wait"
git config --global pull.rebase true

# Install Starship
curl -o starship_install.sh https://starship.rs/install.sh
chmod +x starship_install.sh
./starship_install.sh -b /opt/dev/bin/user -y

# Install OhMyZSH
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
# Configure ZSH Profile
ln -sf ~/dotfiles/zshrc ~/.zshrc

# Install Extensions
EXTENSIONS_DIR=/home/${USER}/.vscode-server/extensions

# Extension: GitLens
/usr/bin/code --extensions-dir="${EXTENSIONS_DIR}" --install-extension "eamodio.gitlens"

# Extension: Github Pull Request
/usr/bin/code --extensions-dir="${EXTENSIONS_DIR}" --install-extension "github.vscode-pull-request-github"

# Extension: Highlighting
/usr/bin/code --extensions-dir="${EXTENSIONS_DIR}" --install-extension "jduponchelle.rainbow-end"
/usr/bin/code --extensions-dir="${EXTENSIONS_DIR}" --install-extension "byi8220.indented-block-highlighting"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

